FROM docker.io/nvidia/cuda:12.6.0-devel-ubuntu22.04

# Install only the minimum system dependencies required to build cuVSLAM and the Python wheel
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    python3-pip \
    python3-dev \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip build wheel
